<a href="https://colab.research.google.com/github/2303A51085/B2_PFDS_1085/blob/main/Lab3Aug14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

add_result = np.add(A, B)
sub_result = np.subtract(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("\nAddition (A + B):\n", add_result)
print("\nSubtraction (A - B):\n", sub_result)

row, col = 0, 0
print(f"\nVerification for element (0,0): {A[row][col]} + {B[row][col]} = {add_result[row][col]}")
print(f"Verification for element (0,0): {A[row][col]} - {B[row][col]} = {sub_result[row][col]}")


Matrix A:
 [[2 6 1]
 [5 6 8]
 [7 3 4]]
Matrix B:
 [[4 3 3]
 [6 5 7]
 [3 8 1]]

Addition (A + B):
 [[ 6  9  4]
 [11 11 15]
 [10 11  5]]

Subtraction (A - B):
 [[-2  3 -2]
 [-1  1  1]
 [ 4 -5  3]]

Verification for element (0,0): 2 + 4 = 6
Verification for element (0,0): 2 - 4 = -2


In [2]:
import numpy as np


A = np.random.randint(1, 10, (3, 2))
B = np.random.randint(1, 10, (2, 3))

print("Matrix A (3x2):\n", A)
print("Matrix B (2x3):\n", B)


C = np.dot(A, B)
print("\nDot Product Result (3x3):\n", C)



manual_calc = A[0][0] * B[0][0] + A[0][1] * B[1][0]
print(f"\nManual calculation for C[0][0]: {manual_calc}")

Matrix A (3x2):
 [[7 2]
 [3 7]
 [2 6]]
Matrix B (2x3):
 [[7 7 3]
 [2 8 7]]

Dot Product Result (3x3):
 [[53 65 35]
 [35 77 58]
 [26 62 48]]

Manual calculation for C[0][0]: 53
