<a href="https://colab.research.google.com/github/2303A51085/B2_PFDS_1085/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
one_dimensional_array = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:", one_dimensional_array)

two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\nTwo-dimensional array:\n", two_dimensional_array)

One-dimensional array: [1 2 3 4 5]

Two-dimensional array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

arr_sum = arr1 + arr2
print("\nSum of arrays:\n", arr_sum)

arr_diff = arr1 - arr2
print("\nDifference of arrays:\n", arr_diff)

arr_product = arr1 * arr2
print("\nElement-wise product of arrays:\n", arr_product)

arr_division = arr1 / arr2
print("\nElement-wise division of arrays:\n", arr_division)


Sum of arrays:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Difference of arrays:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise product of arrays:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise division of arrays:
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [ ]:
arr_transpose = arr1.T
print("\nTranspose of arr1:\n", arr_transpose)

arr_dot_product = np.dot(arr1, arr2)
print("\nDot product of arr1 and arr2:\n", arr_dot_product)

arr_cross_product = np.cross(arr1, arr2)
print("\nCross product of arr1 and arr2:\n", arr_cross_product)


Transpose of arr1:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Dot product of arr1 and arr2:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Cross product of arr1 and arr2:
 [[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [ ]:

zeros_array = np.zeros((3, 3))
print("\nArray of zeros:\n", zeros_array)

ones_array = np.ones((3, 3))
print("\nArray of ones:\n", ones_array)


Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import random

In [ ]:
random_array = np.random.rand(2, 3)
print("\nRandom array:\n", random_array)

random_int_array = np.random.randint(1, 10, size=(2, 3))
print("\nRandom integer array:\n", random_int_array)


Random array:
 [[0.11503381 0.77001802 0.030741  ]
 [0.36967545 0.8059754  0.98285617]]

Random integer array:
 [[1 3 2]
 [5 3 7]]


In [ ]:
aray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nArray size:", aray.size)
print("Array shape:", aray.shape)
print("Array dimensions:", aray.ndim)
print("Array data type:", aray.dtype)
print("\nArray contents:\n", aray)



Array size: 9
Array shape: (3, 3)
Array dimensions: 2
Array data type: int64

Array contents:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
Brodcasting_example = np.array([[1, 2], [3, 4]], dtype=np.float64)
print("\nBroadcasting example:\n", Brodcasting_example)


Broadcasting example:
 [[1. 2.]
 [3. 4.]]
